#!/bin/bash

if [ $# != 1 ]
then
        echo "Usage: ./all rename | backup | reset | rm"
        exit 0
fi

if [ $1 == "rename" ]
then
	rename 's/\.txt/\.log/' *.txt
elif [ $1 == "backup" ] 
then
	find *.log -exec cp {} {}.bak \;
elif [ $1 == "reset" ]
then
	rename 's/\.log$/\.txt/' *.log
elif [ $1 == "rm" ]
then
	find *.bak -exec rm {} \;
else 
	echo "not support."
fi

